### ISSUE TITLE
Add libxlsxwriter topic to the GitHub project metadata

### ISSUE THREAD

**Issue by jmcnamara** [gekola/xlsxwriter-rb#1]
Hi,

Could you add libxlsxwriter as a "topic" metadata to your project so that users can find wrappers in different languages.

Topic/Metadata are shown at the top of the project: https://github.com/jmcnamara/libxlsxwriter

Other examples: https://github.com/search?q=topic%3Alibxlsxwriter&type=Repositories

I'll probably add a section on language wrappings to the libxlsxwriter documentation.

Thanks,

John

**Comment by gekola** [comment]
Hello.

Sorry for the delay in response, somehow i was not the watchers list of my own repository so i did not receive a notification on the issue.

I added the "topic" as you described.

Thank you for the awesome library.

Cheers,
Nick

**Comment by jmcnamara** [comment]
Thank you. Closing.
